
name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true



      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: 安装依赖
        run: npm ci

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > docs/.vuepress/dist/.nojekyll
          rm -rf docs/.vuepress/dist/intro.html
          rm -rf docs/.vuepress/dist/slide.html
          rm -rf docs/.vuepress/dist/home.html
          rm -rf docs/.vuepress/dist/timeline/
          rm -rf docs/.vuepress/dist/category/
          rm -rf docs/.vuepress/dist/star/
          rm -rf docs/.vuepress/dist/slide/
          rm -rf docs/.vuepress/dist/encrypted/
          rm -rf docs/.vuepress/dist/article/
          rm -rf docs/.vuepress/dist/tag/
          rm -rf docs/.vuepress/dist/zh/timeline/
          rm -rf docs/.vuepress/dist/zh/category/
          rm -rf docs/.vuepress/dist/zh/star/
          rm -rf docs/.vuepress/dist/zh/slide/
          rm -rf docs/.vuepress/dist/zh/encrypted/
          rm -rf docs/.vuepress/dist/zh/article/
          rm -rf docs/.vuepress/dist/zh/tag/

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: gh-pages
          folder: docs/.vuepress/dist
